from video_processing.motion_detector import motion_detector, csv_name_creator, FPS, resizing,timestamping
from video_processing.getting_coordinates_manual_CLASS import Rat_coords
from video_processing.motion_detector_MVMwriter import motion_detector_MVMwriter

from video_processing.realTime_plotting_CLASS import Rat_mvm
# from .realTime_plotting_CLASS import Rat_mvm
